version: '3.7'
services:
    app:
        build: .
        depends_on:
            - db
        command: sleep infinity
        ports:
            - "8000:8000"
        volumes:
            - type: bind
              source: ./
              target: /home/app/app/
        environment:
            DB_NAME: 'db'
            DB_USER: 'db'
            DB_PASSWORD: 'db'
            DB_HOST: 'db'
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: db
            POSTGRES_PASSWORD: db
