version: '3.7'
services:
    app:
        build: .
        depends_on:
            - db
        command: sleep infinity
        ports:
            - "8000:8000"
        volumes:
            - type: bind
              source: ./
              target: /home/app/app/
        environment:
            # Remember to also update .circleci/config.yml
            DB_NAME: 'db'
            DB_USER: 'db'
            DB_PASSWORD: 'db'
            DB_HOST: 'db'
            DJANGO_SETTINGS_MODULE: 'config.settings.dev'
            PATH: '/home/app/.local/bin:/usr/bin:/bin'
            PYTHONPATH: '/home/app/app'
            SECRET_KEY: 'secret'
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: db
            POSTGRES_PASSWORD: db
