info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/maps/bydomain/:
    get:
      description: Return map matching the request HTTP Host header.
      operationId: maps_bydomain
      parameters:
      - in: query
        name: expand
        schema:
          description: Expand places list
          title: ''
          type: string
      tags:
      - maps
  /api/maps/{id}/:
    get:
      operationId: maps_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this map.
          title: id
          type: string
      - in: query
        name: expand
        schema:
          description: Expand places list
          title: ''
          type: string
      tags:
      - maps
  /api/places/:
    get:
      description: Return places belonging to the specified map_id.
      operationId: places_list
      parameters:
      - in: query
        name: map_id
        required: true
        schema:
          description: Map identifier
          title: ''
          type: string
      tags:
      - places
  /api/places/{id}/:
    get:
      operationId: places_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this place.
          title: id
          type: string
      tags:
      - places
servers:
- url: http://localhost:8000/
