info:
  title: 'Amigomap API'
  version: ''
openapi: 3.0.3
paths:
  /api/maps/bydomain/:
    get:
      parameters:
      - in: query
        name: expand
        description: Expand places list
        schema:
          type: string
          enum:
            - places
      responses:
        '200':
          description: map matching the request HTTP Host header
        '404':
          description: map not found
      tags:
      - maps
  /api/maps/{id}/:
    get:
      parameters:
      - in: path
        name: id
        description: UUID identifying this map.
        required: true
        schema:
          title: id
          type: string
      - in: query
        name: expand
        description: Expand places list
        schema:
          type: string
          enum:
            - places
      responses:
        '200':
          description: map
      tags:
      - maps
  /api/places/:
    get:
      parameters:
      - in: query
        name: map_id
        description: Map identifier
        required: true
        schema:
          type: string
      responses:
        '200':
          description: places for the given map
      tags:
      - places
  /api/places/{id}/:
    get:
      parameters:
      - in: path
        name: id
        description: UUID identifying this place.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: place
      tags:
      - places
servers:
- url: http://localhost:8000/
