# Generated by Django 2.1.4 on 2018-12-26 14:22

from django.db import migrations

import app.fields


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="place", name="color", field=app.fields.ColorField()
        ),
        migrations.AddField(
            model_name="tag", name="color", field=app.fields.ColorField()
        ),
    ]
