# Generated by Django 2.1.4 on 2018-12-17 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemap',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='_placemap_admin_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placemap',
            name='viewer',
            field=models.ManyToManyField(blank=True, related_name='_placemap_viewer_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
