# Generated by Django 2.1.4 on 2018-12-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181217_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='placemap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PlaceMap'),
            preserve_default=False,
        ),
    ]
