# Generated by Django 2.1.4 on 2018-12-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_placemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='placemap',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=32),
        ),
    ]
