# Generated by Django 2.1.7 on 2019-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("app", "0005_auto_20190207_2012")]

    operations = [migrations.RemoveField(model_name="place", name="color")]
